<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * http://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development <support@shopmodule.com>
 * @link      http://www.oxidmodule.com
 */

$sLangName = "Deutsch";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(
    'charset'                                     => 'UTF-8',
    //Navigation
    'd3mxwatermark'                               => "<i class='fas fa-images'></i> Watermark",
    'd3mxwatermark_settings'                      => 'Settings',
    'd3tbclwatermark_main'                        => 'Main',
    'd3tbclwatermark_imagetypes'                  => 'Image formats',
    'd3tbclwatermark_licence'                     => 'Support',
    // Tabinhalte Bildformate
    'D3_WATERMARK_FORMAT_GLOBAL'                  => 'global settings',
    'D3_WATERMARK_FORMAT_ICON'                    => 'icons',
    'D3_WATERMARK_FORMAT_CATEGORY_ICON'           => 'category icons',
    'D3_WATERMARK_FORMAT_MANUFACTURER_ICON'       => 'brand icons',
    'D3_WATERMARK_FORMAT_VENDOR_ICON'             => 'vendor icons',
    'D3_WATERMARK_FORMAT_CATEGORY_PROMO_ICON'     => 'homepage category icons',
    'D3_WATERMARK_FORMAT_THUMB'                   => 'thumbnails',
    'D3_WATERMARK_FORMAT_CATEGORY_THUMB'          => 'category thumbnails',
    'D3_WATERMARK_FORMAT_PIC1'                    => 'picture 1',
    'D3_WATERMARK_FORMAT_PIC2'                    => 'picture 2',
    'D3_WATERMARK_FORMAT_PIC3'                    => 'picture 3',
    'D3_WATERMARK_FORMAT_PIC4'                    => 'picture 4',
    'D3_WATERMARK_FORMAT_PIC5'                    => 'picture 5',
    'D3_WATERMARK_FORMAT_PIC6'                    => 'picture 6',
    'D3_WATERMARK_FORMAT_PIC7'                    => 'picture 7',
    'D3_WATERMARK_FORMAT_PIC8'                    => 'picture 8',
    'D3_WATERMARK_FORMAT_PIC9'                    => 'picture 9',
    'D3_WATERMARK_FORMAT_PIC10'                   => 'picture 10',
    'D3_WATERMARK_FORMAT_PIC11'                   => 'picture 11',
    'D3_WATERMARK_FORMAT_PIC12'                   => 'picture 12',
    'D3_WATERMARK_FORMAT_ZOOM1'                   => 'zoom 1',
    'D3_WATERMARK_FORMAT_ZOOM2'                   => 'zoom 2',
    'D3_WATERMARK_FORMAT_ZOOM3'                   => 'zoom 3',
    'D3_WATERMARK_FORMAT_ZOOM4'                   => 'zoom 4',
    'D3_WATERMARK_FORMAT_ZOOM5'                   => 'zoom 5',
    'D3_WATERMARK_FORMAT_ZOOM6'                   => 'zoom 6',
    'D3_WATERMARK_FORMAT_ZOOM7'                   => 'zoom 7',
    'D3_WATERMARK_FORMAT_ZOOM8'                   => 'zoom 8',
    'D3_WATERMARK_FORMAT_ZOOM9'                   => 'zoom 9',
    'D3_WATERMARK_FORMAT_ZOOM10'                  => 'zoom 10',
    'D3_WATERMARK_FORMAT_ZOOM11'                  => 'zoom 11',
    'D3_WATERMARK_FORMAT_ZOOM12'                  => 'zoom 12',
    'D3_WATERMARK_FORMAT_MASTER'                  => 'picture (masterpicture)',
    'D3_WATERMARK_FORMAT_ZOOM'                    => 'zoom',
    // Tabinhalte Stamm
    'D3_WATERMARK_MAIN_WMIMAGE'                   => 'image overlay',
    'D3_WATERMARK_MAIN_WMTEXT'                    => 'text overlay',
    'D3_WATERMARK_MAIN_SETTINGS'                  => 'settings',
    'D3_WATERMARK_MAIN_FILEUPLOAD'                => 'upload and previewing file',
    'D3_WATERMARK_MAIN_SUPPORTED_PICS_HELP'       => 'Currently the following image formats are supported.<br> PNG, JPG, GIF',
    'D3_WATERMARK_DELETE_ALLGENPIX'               => 'delete',
    'D3_WATERMARK_DELETE_ALLGENPIX_MESSAGE'       => 'Do you want to remove the generated images?',
    'D3_WATERMARK_DELETE_ALLGENPIX_HELP'          => 'With this option you have the possibility to remove the images already generated by the shop. <br><br>This is necessary, for example, if you have uploaded a new watermark image, changed settings, or if you have already generated images in the shop before activating the module.',
    'D3_WATERMARK_MAIN_IMG_REQUIRED'              => 'Please upload a watermark image first.',
    'D3_WATERMARK_MAIN_PREVIEW'                   => 'preview:',
    'D3_WATERMARK_MAIN_FITTRANSPARENCY'           => 'Use image without additional transparency',
    'D3_WATERMARK_MAIN_NEWTRANSPARENCY'           => 'Apply the following transparency',
    'D3_WATERMARK_MAIN_TRANSPARENCYDESC'          => 'The value is given in % (percent). The value corresponds to the degree of transparency. The higher the value, the more opaque the watermark. <br>D.h. 0 = invisible, 100 = opaque',
    'D3_WATERMARK_MAIN_FORMATSELECT'              => 'Select image format:',
    'D3_WATERMARK_MAIN_FORMATACTIVE'              => 'embed watermark',
    'D3_WATERMARK_MAIN_FORMATNOTICE'              => 'For each image format, please set whether and how this watermark is to be used. To do this, switch to the tab "Image formats".',
    'D3_WATERMARK_MAIN_DEMO'                      => 'You use the module in test mode. The watermark is a given image. If you want to use your own watermark image instead, please purchase the module.',
    'D3_WATERMARK_MAIN_INSERTTYPE'                => 'fitting',
    'D3_WATERMARK_MAIN_INSERTTYPE_FULLSIZE'       => 'largest possible in picture',
    'D3_WATERMARK_MAIN_INSERTTYPE_FITVERTICAL'    => 'vertically',
    'D3_WATERMARK_MAIN_INSERTTYPE_FITHORIZONTAL'  => 'horizontal',
    'D3_WATERMARK_MAIN_INSERTTYPE_DIRECTPOS'      => 'position directly',
    'D3_WATERMARK_MAIN_INSERTTYPE_DIRECTPOS_SETS' => 'further settings (if necessary)',
    'D3_WATERMARK_MAIN_INSERTPOS_CENTER'          => 'centered',
    'D3_WATERMARK_MAIN_INSERTPOS_TOP'             => 'centered on top',
    'D3_WATERMARK_MAIN_INSERTPOS_TOPRIGHT'        => 'top right',
    'D3_WATERMARK_MAIN_INSERTPOS_RIGHT'           => 'right centered',
    'D3_WATERMARK_MAIN_INSERTPOS_BOTTOMRIGHT'     => 'bottom right',
    'D3_WATERMARK_MAIN_INSERTPOS_BOTTOM'          => 'bottom centered',
    'D3_WATERMARK_MAIN_INSERTPOS_BOTTOMLEFT'      => 'bottom left',
    'D3_WATERMARK_MAIN_INSERTPOS_LEFT'            => 'left center',
    'D3_WATERMARK_MAIN_INSERTPOS_TOPLEFT'         => 'top left',
    'D3_WATERMARK_MAIN_INSERT_WIDTH'              => 'width:',
    'D3_WATERMARK_MAIN_INPUTTEXT'                 => 'Watermark text:',
    'D3_WATERMARK_MAIN_TEXTCOLOR'                 => 'text color',
    'D3_WATERMARK_MAIN_HELPLINK'                  => 'Fragen-zu-speziellen-Modulen/Wasserzeichen/',
    // Popup - Buttons / Text
    'D3_WATERMARK_NEW_WATERMARKPICTURE'           => 'A new image for the watermark was uploaded. To use the new watermark, the already generated images must be removed.',
    'D3_WATERMARK_NEW_WATERMARKSETTINGS'           => 'New settings have been saved. To update the implemented watermark, the already generated images must be removed.',
    'D3_WATERMARK_CLEAR_GENERATED_PICTURES'       => 'Do you want to do this now?',
    'D3_WATERMARK_BUTTON_OK'                      => 'Perform now',
    'D3_WATERMARK_BUTTON_NOT_YET'                 => 'Perform manually later',
    // Fehlertexte
    'D3_WATERMARK_INACTIVE_NOTICE'                => 'Module is not active. Please activate this under: Module Connector -> Module Administration',
    'D3_WATERMARK_FAILUPLOAD_11'                  => 'Please check the file format you uploaded. Allowed formats are "gif", "jpg" and "png".',
    'D3_WATERMARK_CHANGED_HTACCESS'               => "NOTE: The installation included adjustments to the shop's .htaccess file.",
    // faeture
    'D3_WATERMARK_FORMAT_PRODUCTPIX'              => 'product pictures',
    'D3_WATERMARK_FORMAT_PRODUCTZOOMPIX'          => 'product zoom pictures',
    'D3_WATERMARK_FORMAT_OTHERPIX'                => 'other pictures',

    'D3_WATERMARK_CLRTMP_GENIMGS_SUCC'            => 'The generated images have been deleted.',
);
